=== carlosboniniklison/CFGS/ejercicios/LMSGI/LMSGI-2020/xml/ej2-bienformado.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="filmoteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="pelicula"/>
                <xs:element ref="autor"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pelicula">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="director" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="titulo"/>
            </xs:sequence>
            <xs:attribute name="genero" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="director" type="xs:string"/>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="autor" type="xs:NCName"/>
    <xs:element name="genero">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Terror"/>
          <xs:enumeration value="Comedia"/>
          <xs:enumeration value="Drama"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
</xs:schema>

=== carlosboniniklison/CFGS/ejercicios/LMSGI/previos/xml/ej2-bienformado.xml
<?xml version="1.0" encoding="UTF-8"?>
<filmoteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///G:/xampp/htdocs/profesorcarlos.es/1DAW-LLMM/xml/ej2-bienformado.xsd">
	<pelicula genero="Comedia">	  
	  <director>Billy Wilder</director>
	  <titulo>Con faldas y a lo loco</titulo>
	</pelicula>
	<pelicula genero="Terror">
	  <director>Malcolm D. Lee</director>
	  <director>Kinen Ivory Wyanne</director>
	  <director>David Zucher</director>
	  <titulo>Scary Movie</titulo>
	</pelicula>
	<pelicula genero="Drama">
	  <titulo>Sopa de ganso</titulo>
	</pelicula>
	<autor>barto</autor>
</filmoteca>
