=== carlosboniniklison/CFGS/ejercicios/LMSGI/LMSGI-2020/ExmenFinalResuelto-2020/Act2-Carrillo-Cristina.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Cristina Carrillo Reyes 1 DAM-M -->
<!-- DNI 74696006-X-->
<!-- Para hacerlo he seguido el ejercicio que hicimos en clase -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="usuarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="usuario" minOccurs="0" maxOccurs="unbounded"><!-- usuarios a insertar de 0 a ilimitados-->
          <xs:complexType>
            <xs:sequence>
              <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="2"/><!-- de uno a dos apellidos-->
              <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="2"/><!-- de uno a dos nombres-->
              <xs:element name="fecha_de_registro" type="xs:string" minOccurs="1" maxOccurs="1"/><!-- minimo debe haber una fecha de registro-->
              <xs:element name="username" type="xs:string" minOccurs="1" maxOccurs="1"/><!-- minimo debe haber un username-->
              <xs:element name="fecha_de_baja" type="xs:string" minOccurs="0" maxOccurs="1"/><!-- puede no haber,o haber uno-->
            </xs:sequence>
            <xs:attribute name="estado" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== carlosboniniklison/CFGS/ejercicios/LMSGI/LMSGI-2020/ExmenFinalResuelto-2020/Act1-Carrillo-Cristina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Cristina Carrillo Reyes 1 DAM-M -->
<!-- DNI 74696006-X-->
<!-- Para hacerlo he seguido el ejercicio que hicimos en clase -->
<?xml-stylesheet type="text/xsl" href="Act4-Carrillo-Cristina.xsl"?> <!-- ejercicio 4 asociado al xml-->
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Act2-Carrillo-Cristina.xsd"> <!-- ejercicio  2  asociado al xml-->
  <usuario estado="validado"><!-- estado no es una etiqueta, es un atributo-->
    <apellido>Carrillo</apellido><!--etiqueta apellido-->
    <nombre>Cristina</nombre><!--etiqueta nombre-->
    <fecha_de_registro>21-01-2020</fecha_de_registro><!--etiqueta fecha de registro-->
    <username>Cristi</username><!--etiqueta username-->
    <fecha_de_baja>22-03-2020</fecha_de_baja><!--etiqueta fecha de baja-->
  </usuario>
  <usuario estado="inactivo">
    <apellido>Ruiz</apellido>
    <nombre>Javier</nombre>
    <fecha_de_registro>12-02-1998</fecha_de_registro>
    <username>Javi</username>
    <fecha_de_baja>16-05-2001</fecha_de_baja>
  </usuario>
  <usuario estado="activo">
    <apellido>Aviles</apellido>
    <nombre>Jose Manuel</nombre>
    <fecha_de_registro>06-08-2017</fecha_de_registro>
    <username>Koalote</username>
    <fecha_de_baja>22-03-2020</fecha_de_baja>
  </usuario>
  <usuario estado="inactivo">
    <apellido>Sanchez</apellido>
    <nombre>Maria</nombre>
    <fecha_de_registro>09-07-2014</fecha_de_registro>
    <username>Mary</username>
    <fecha_de_baja>08-11-2015</fecha_de_baja>
  </usuario>
  <usuario estado="validado">
    <apellido>Gato</apellido>
    <nombre>Teodoro</nombre>
    <fecha_de_registro>14-12-1997</fecha_de_registro>
    <username>Teo</username>
    <fecha_de_baja>15-07-2008</fecha_de_baja>
  </usuario>
</usuarios>
